---
- name: restart zookeeper
  shell: /bin/systemctl daemon-reload
  notify: restart zookeeper 2

- name: restart zookeeper 2
  service: name=zookeeper state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted
